"""empty message

Revision ID: 6d5fb9b1b941
Revises: 4820ea999e90
Create Date: 2018-07-27 17:18:20.827190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d5fb9b1b941'
down_revision = '4820ea999e90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faq_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=8), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('attachment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question')
    )
    op.create_table('integration_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=8), nullable=True),
    sa.Column('short_description', sa.Text(length=125), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('attachment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_description'),
    sa.UniqueConstraint('title')
    )
    op.create_table('shopping_cart_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=8), nullable=True),
    sa.Column('short_description', sa.Text(length=125), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('attachment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_description'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shopping_cart_page')
    op.drop_table('integration_page')
    op.drop_table('faq_page')
    # ### end Alembic commands ###
